=== salmander/open-lims/open-lims/templates/OLDL/oldl.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT OLDL (HEAD?,REQUIRED?,BODY?)>

<!ELEMENT HEAD (ID|TITLE|VERSION?|AUTHOR?|DESC?|LOCATION?|MANUFACTURER?|EXPIRY?)*>
<!ELEMENT REQUIRED (ITEM*,CLASS*)>
<!ELEMENT BODY (ITEM|CLASS|STATUS|EXTENSION)*>

<!ELEMENT STATUS (ITEM|ITEMI|CLASS|EXTENSION)*>

<!ELEMENT ITEM (TYPE|INFORMATION|CATEGORY|ITEMI)*>
<!ELEMENT ITEMI EMPTY>

<!ELEMENT CLASS (INFORMATION)*>

<!ELEMENT INFORMATION EMPTY>

<!ELEMENT TYPE EMPTY>
<!ELEMENT CATEGORY EMPTY>

<!ELEMENT EXTENSION (FILTER)>

<!ELEMENT FILTER EMPTY>

<!ELEMENT ID (#PCDATA)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT VERSION (#PCDATA)>
<!ELEMENT AUTHOR (#PCDATA)>
<!ELEMENT DESC (#PCDATA)>
<!ELEMENT LOCATION EMPTY>
<!ELEMENT MANUFACTURER EMPTY>
<!ELEMENT EXPIRY EMPTY>

<!ATTLIST 	OLDL
	type			CDATA						#IMPLIED
>	

<!ATTLIST 	STATUS
	id				CDATA						#REQUIRED
	requirement		(force|optional)    		#IMPLIED
>        

<!ATTLIST 	ITEM
	type	        CDATA    					#IMPLIED
	classify	    (force|optional|forbidden)	#IMPLIED
	occurrence		(once|multiple)				#IMPLIED      
	requirement		(force|optional)			#IMPLIED   
	class			CDATA						#IMPLIED      
	name			CDATA						#IMPLIED      
	pos_id			CDATA						#IMPLIED
	folder			CDATA						#IMPLIED
	inherit			(all|none)					#IMPLIED
	dialog			(window|page)				#IMPLIED
>       

<!ATTLIST 	ITEMI
	pos_id			CDATA						#REQUIRED
	parent_pos_id   CDATA						#IMPLIED
	parent_status   CDATA						#IMPLIED
	parent_status   (true|false)				#IMPLIED   
	dialog			(window|page)				#IMPLIED
>   

<!ATTLIST 	TYPE
	id				CDATA						#REQUIRED
>	

<!ATTLIST 	CATEGORY
	id				CDATA						#REQUIRED
>	

<!ATTLIST 	CLASS
	name			CDATA						#REQUIRED
>
      
<!ATTLIST 	INFORMATION
	keywords		(keywords)					#IMPLIED	
	description		(description)				#IMPLIED
>	

<!ATTLIST 	EXTENSION
	identifier		CDATA						#REQUIRED
	requirement		(force|optional)			#IMPLIED 
	occurrence		(once|multiple)				#IMPLIED 
>

<!ATTLIST 	FILTER
	status			CDATA						#REQUIRED
	type			CDATA						#IMPLIED
>

<!ATTLIST 	LOCATION
	requirement		(force|optional)			#IMPLIED
>

<!ATTLIST 	MANUFACTURER
	requirement		(force|optional)			#IMPLIED
>

<!ATTLIST 	EXPIRY
	requirement		(force|optional)			#IMPLIED
>

=== salmander/open-lims/open-lims/templates/OLDL/project_microarray_standard.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OLDL PUBLIC "-//OLDL 0.4//EN" "http://doctype.open-lims.org/oldl.dtd" >
<OLDL>
	<HEAD>
		<ID>10001</ID>
	 	<TITLE>MicroArray - Standard</TITLE>
		<DESC>Standard-Template for MicroArray based Projects</DESC>
		<VERSION>draft</VERSION>
		<AUTHOR>The Open-LIMS Project</AUTHOR>
	</HEAD>
	<REQUIRED>
		<ITEM type="value">
          <TYPE id="10000"></TYPE>
   		 </ITEM>
	</REQUIRED>
	<BODY>
		<STATUS id="10001">
			<ITEM type="sample" occurrence="multiple" inherit="all">
            	<TYPE id="10000"></TYPE>
     		</ITEM>
		</STATUS>
		<STATUS id="10002">
  			<ITEM type="sample" occurrence="multiple">
         		<TYPE id="11000"></TYPE>
    		</ITEM>		
		</STATUS>
		<STATUS id="10003">
			<ITEM type="value">
         		<TYPE id="10003"></TYPE>
      		</ITEM>
			<ITEM type="equipment" occurrence="multiple" name="Add Used Hardware">
				<CATEGORY id="1000" />
			</ITEM>
		</STATUS>
		<STATUS id="10004">
			<ITEM type="equipment" occurrence="multiple" name="Add Hybridisation Hardware">
				<CATEGORY id="1000" />
			</ITEM>
		</STATUS>
		<STATUS id="10005">
			<ITEM type="equipment" occurrence="multiple" name="Add Washing Hardware">
				<CATEGORY id="1000" />
			</ITEM>
		</STATUS>
		<STATUS id="10006">
		  	<ITEMI parent_status="10002" parent_pos_id="0" pos_id="0"></ITEMI>
			<ITEMI parent_status="10002" parent_pos_id="0" pos_id="2" takeover="true"></ITEMI>
		</STATUS>
		<STATUS id="10007">
			<ITEMI parent_status="10002" parent_pos_id="0" pos_id="3" takeover="true"></ITEMI>
		</STATUS>
		<STATUS id="10008">
			<ITEMI parent_status="10002" parent_pos_id="0" pos_id="1"></ITEMI>
		</STATUS>
		<STATUS id="10009">
			<EXTENSION identifier="MICROARRAY_ANALYSIS" occurrence="multiple">
				<FILTER status="10002" type="sample" />
				<FILTER status="10008" type="file" />
			</EXTENSION>
			<ITEM type="file" occurrence="multiple" name="Add SAM Result"></ITEM>
		</STATUS>
	</BODY>
</OLDL>

=== salmander/open-lims/open-lims/templates/OLDL/project_microscopy_image_master.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OLDL PUBLIC "-//OLDL 0.4//EN" "http://doctype.open-lims.org/oldl.dtd" >
<OLDL>
	<HEAD>
		<ID>29000</ID>
	 	<TITLE>Microscopy - Image (Parent/Master)</TITLE>
		<DESC>Master/Parent-Template for Microsopy Imaging Experiments</DESC>
		<VERSION>draft</VERSION>
		<AUTHOR>The Open-LIMS Project</AUTHOR>
	</HEAD>
 	<REQUIRED>  
  	</REQUIRED>
	<BODY>
		<STATUS id="100">
			<ITEM type="file" name="Add Shortlist RAW File" folder="shortlist raw" requirement="optional" occurrence="multiple"></ITEM>  
			<ITEM type="file" name="Add TIF File" folder="tif" requirement="optional" occurrence="multiple"></ITEM>
		</STATUS>
	</BODY>
</OLDL>

=== salmander/open-lims/open-lims/templates/OLDL/sample_rna.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OLDL PUBLIC "-//OLDL 0.4//EN" "http://doctype.open-lims.org/oldl.dtd" >
<OLDL type="sample">
	<HEAD>
		<ID>10000</ID>
	 	<TITLE>RNA</TITLE>
		<DESC>RNA Template</DESC>
		<VERSION>draft</VERSION>
		<AUTHOR></AUTHOR>
		<LOCATION requirement="optional" />
		<MANUFACTURER requirement="optional" />
	</HEAD>
	<BODY>
		<ITEM type="equipment" occurrence="multiple" name="Add Used Hardware">
			<CATEGORY id="1000" />
		</ITEM>
		<ITEM type="value" name="Add RNA Parameters">
    		<TYPE id="10001"></TYPE>
		</ITEM>   
		<ITEM type="file" occurrence="multiple" requirement="optional" name="Add BioAnalyzer File"></ITEM>    
	</BODY>
</OLDL>

=== salmander/open-lims/open-lims/templates/OLDL/sample_microscopy_specimen_fixed_sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OLDL PUBLIC "-//OLDL 0.4//EN" "http://doctype.open-lims.org/oldl.dtd" >
<OLDL type="sample">
	<HEAD>
		<ID>20100</ID>
	 	<TITLE>Microscopy Specimen - Fixed Sample</TITLE>
		<DESC>Template for fixed-sample microscopy coverslip</DESC>
		<VERSION>draft</VERSION>
		<AUTHOR></AUTHOR>
	</HEAD>
	<REQUIRED>
		<ITEM type="value">
          <TYPE id="20101"></TYPE>
    	</ITEM>
	</REQUIRED>
	<BODY>
     	<ITEM type="parentsample" requirement="optional" occurrence="multiple" inherit="all">
     	</ITEM>      
	</BODY>
</OLDL>

=== salmander/open-lims/open-lims/templates/OLDL/project_microarray_parent.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OLDL PUBLIC "-//OLDL 0.4//EN" "http://doctype.open-lims.org/oldl.dtd" >
<OLDL>
	<HEAD>
		<ID>19000</ID>
		<TITLE>MicroArray - Parent Project</TITLE>
		<DESC>Parent Project for different Microarray projects</DESC>
		<VERSION>draft</VERSION>
		<AUTHOR></AUTHOR>
	</HEAD>
	<REQUIRED>  
  	</REQUIRED>
	<BODY>
		<STATUS id="100"></STATUS>
	</BODY>
</OLDL>

=== salmander/open-lims/open-lims/templates/OLDL/project_microscopy_image.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OLDL PUBLIC "-//OLDL 0.4//EN" "http://doctype.open-lims.org/oldl.dtd" >
<OLDL>
	<HEAD>
		<ID>20001</ID>
	 	<TITLE>Microscopy - Image</TITLE>
		<DESC>Standard-Template for Microsopy Imaging Experiments</DESC>
		<VERSION>draft</VERSION>
		<AUTHOR>The Open-LIMS Project</AUTHOR>
	</HEAD>
	<REQUIRED>
	</REQUIRED>
	<BODY>
		<STATUS id="20001">
			<ITEM type="sample" name="Add Specimen">
            	<TYPE id="20100"></TYPE>
            	<TYPE id="20110"></TYPE>
            	<TYPE id="20120"></TYPE>
     		</ITEM>
		</STATUS>
		<STATUS id="20002">
			<ITEM type="equipment" name="Add Used Hardware" occurrence="multiple">
		         <TYPE id="3"></TYPE>
		         <CATEGORY id="1003"></CATEGORY>              
		         <CATEGORY id="1007"></CATEGORY>
		    </ITEM>       
		    <ITEM type="equipment" name="Add Used Software" occurrence="multiple">
		         <TYPE id="3"></TYPE>
		         <CATEGORY id="1008"></CATEGORY>
		    </ITEM>   
		</STATUS>
		<STATUS id="20003">
  			<ITEM type="file" name="Add Main/RAW File" folder="main" occurrence="multiple"></ITEM>
      		<ITEM type="file" name="Add Shortlist RAW File" folder="shortlist raw" requirement="optional" occurrence="multiple"></ITEM>        
		    <ITEM type="file" name="Add TIF File" folder="tif" requirement="optional" occurrence="multiple"></ITEM>      
		    <ITEM type="file" name="Add Configuration File" folder="tif" requirement="optional" occurrence="multiple"></ITEM>
		    <ITEM type="value" requirement="optional">            
		         <TYPE id="20001"></TYPE>
		    </ITEM> 
		</STATUS>
	</BODY>
</OLDL>

=== salmander/open-lims/open-lims/templates/OLDL/project_general_master.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OLDL PUBLIC "-//OLDL 0.4//EN" "http://doctype.open-lims.org/oldl.dtd" >
<OLDL>
	<HEAD>
		<ID>100</ID>
		<TITLE>General Master/Parent Project</TITLE>
		<DESC>General Master/Parent Project</DESC>
		<VERSION>draft</VERSION>
		<AUTHOR>The Open-LIMS Project</AUTHOR>
	</HEAD>
 	<REQUIRED>  
  	</REQUIRED>
	<BODY>
		<STATUS id="100"></STATUS>
	</BODY>
</OLDL>

=== salmander/open-lims/open-lims/templates/OLDL/sample_microarray_w_location.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OLDL PUBLIC "-//OLDL 0.4//EN" "http://doctype.open-lims.org/oldl.dtd" >
<OLDL type="sample">
	<HEAD>
		<ID>11001</ID>
	 	<TITLE>MicroArray w. Location</TITLE>
		<DESC>Microarray Template</DESC>
		<VERSION>draft</VERSION>
		<AUTHOR></AUTHOR>
		<LOCATION />
	</HEAD>
  	<REQUIRED>  
     	<ITEM type="parentsample"></ITEM>            
      	<ITEM type="parentsample"></ITEM>
  	</REQUIRED>
	<BODY>
		<ITEM type="file" occurrence="multiple" name="Add TIF-Files"></ITEM>
		<ITEM type="file" occurrence="multiple" name="Add Curated Files"></ITEM>
		<ITEM type="equipment" occurrence="multiple" name="Add Used Scanning-HW">
			<CATEGORY id="1000" />
		</ITEM>
		<ITEM type="equipment" occurrence="multiple" name="Add Used Scanning-SW">
			<CATEGORY id="1001" />
		</ITEM>
	</BODY>
</OLDL>
