=== salmander/open-lims/open-lims/templates/OLDL/oldl.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT OLDL (HEAD?,REQUIRED?,BODY?)>

<!ELEMENT HEAD (ID|TITLE|VERSION?|AUTHOR?|DESC?|LOCATION?|MANUFACTURER?|EXPIRY?)*>
<!ELEMENT REQUIRED (ITEM*,CLASS*)>
<!ELEMENT BODY (ITEM|CLASS|STATUS|EXTENSION)*>

<!ELEMENT STATUS (ITEM|ITEMI|CLASS|EXTENSION)*>

<!ELEMENT ITEM (TYPE|INFORMATION|CATEGORY|ITEMI)*>
<!ELEMENT ITEMI EMPTY>

<!ELEMENT CLASS (INFORMATION)*>

<!ELEMENT INFORMATION EMPTY>

<!ELEMENT TYPE EMPTY>
<!ELEMENT CATEGORY EMPTY>

<!ELEMENT EXTENSION (FILTER)>

<!ELEMENT FILTER EMPTY>

<!ELEMENT ID (#PCDATA)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT VERSION (#PCDATA)>
<!ELEMENT AUTHOR (#PCDATA)>
<!ELEMENT DESC (#PCDATA)>
<!ELEMENT LOCATION EMPTY>
<!ELEMENT MANUFACTURER EMPTY>
<!ELEMENT EXPIRY EMPTY>

<!ATTLIST 	OLDL
	type			CDATA						#IMPLIED
>	

<!ATTLIST 	STATUS
	id				CDATA						#REQUIRED
	requirement		(force|optional)    		#IMPLIED
>        

<!ATTLIST 	ITEM
	type	        CDATA    					#IMPLIED
	classify	    (force|optional|forbidden)	#IMPLIED
	occurrence		(once|multiple)				#IMPLIED      
	requirement		(force|optional)			#IMPLIED   
	class			CDATA						#IMPLIED      
	name			CDATA						#IMPLIED      
	pos_id			CDATA						#IMPLIED
	folder			CDATA						#IMPLIED
	inherit			(all|none)					#IMPLIED
	dialog			(window|page)				#IMPLIED
>       

<!ATTLIST 	ITEMI
	pos_id			CDATA						#REQUIRED
	parent_pos_id   CDATA						#IMPLIED
	parent_status   CDATA						#IMPLIED
	parent_status   (true|false)				#IMPLIED   
	dialog			(window|page)				#IMPLIED
>   

<!ATTLIST 	TYPE
	id				CDATA						#REQUIRED
>	

<!ATTLIST 	CATEGORY
	id				CDATA						#REQUIRED
>	

<!ATTLIST 	CLASS
	name			CDATA						#REQUIRED
>
      
<!ATTLIST 	INFORMATION
	keywords		(keywords)					#IMPLIED	
	description		(description)				#IMPLIED
>	

<!ATTLIST 	EXTENSION
	identifier		CDATA						#REQUIRED
	requirement		(force|optional)			#IMPLIED 
	occurrence		(once|multiple)				#IMPLIED 
>

<!ATTLIST 	FILTER
	status			CDATA						#REQUIRED
	type			CDATA						#IMPLIED
>

<!ATTLIST 	LOCATION
	requirement		(force|optional)			#IMPLIED
>

<!ATTLIST 	MANUFACTURER
	requirement		(force|optional)			#IMPLIED
>

<!ATTLIST 	EXPIRY
	requirement		(force|optional)			#IMPLIED
>

=== salmander/open-lims/open-lims/templates/OLDL/sample_microscopy_specimen_live_imaging.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OLDL PUBLIC "-//OLDL 0.4//EN" "http://doctype.open-lims.org/oldl.dtd" >
<OLDL type="sample">
	<HEAD>
		<ID>20120</ID>
	 	<TITLE>Microscopy Specimen - Live Imaging</TITLE>
		<DESC>Template for live-imaging microscopy coverslip</DESC>
		<VERSION>draft</VERSION>
		<AUTHOR></AUTHOR>
	</HEAD>
	<REQUIRED>
		<ITEM type="value">
          <TYPE id="20103"></TYPE>
    	</ITEM>
	</REQUIRED>
	<BODY>
     	<ITEM type="parentsample" requirement="optional" occurrence="multiple" inherit="all">
     	</ITEM>      
	</BODY>
</OLDL>

=== salmander/open-lims/open-lims/templates/OLDL/sample_general_w_expiry.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OLDL PUBLIC "-//OLDL 0.4//EN" "http://doctype.open-lims.org/oldl.dtd" >
<OLDL type="sample">
	<HEAD>
		<ID>101</ID>
	 	<TITLE>General w. Date of Expiry</TITLE>
		<DESC>General Sample Template</DESC>
		<VERSION>draft</VERSION>
		<AUTHOR></AUTHOR>
		<LOCATION requirement="optional" />
		<MANUFACTURER requirement="optional" />
		<EXPIRY />
	</HEAD>
	<BODY>
      	<ITEM type="parameter">
	 	</ITEM> 
	</BODY>
</OLDL>
